services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - HOST=db
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
